name: Deploy the static website 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Basic testing
        run: echo "Mainak"
      - name: Checkout
        uses: actions/checkout@v4
      